
  - type: Dialog
    name: Collection View Settings Dialog
    scrolled-content: false # pending proper solution, see DSK-343305
    content:
      type: StackLayout
      elements:
        - type: StackLayout
          orientation: horizontal
          name: viewpane_display_style
          elements:
            - type: Button
              name: thumbnail_style
              button-style: toolbar-image
              skin-foreground-image: Collection Thumbnail Style Skin
              fixed-image: true
              action-string: Switch to thumbnail view
            - type: Button
              name: listview_style
              button-style: toolbar-image
              skin-foreground-image: Collection Listview Style Skin
              fixed-image: true
              action-string: Switch to list view
        - type: Separator
          top-margin: 8
          bottom-margin: 8
        - type: Label
          string: D_COLLECTION_DEFAULT_SORTING
          font-weight: bold
        - type: Dropdown
          name: sorting_dropdown
          preferred-width: fill
          elements:
            - string: M_COLLECTION_SORT_BY_DATE
              action-string: Sort Collection View, 0
            - string: M_COLLECTION_SORT_BY_NAME
              action-string: Sort Collection View, 1
       
          

