  - type: Dialog
    name: Speed Dial Configuration Dialog
    scrolled-content: false # pending proper solution, see DSK-343305
    widgets:
      - &PageSuggestionComposite
        type: Composite
        skin-image: Speed Dial Configuration Dialog Page Button
      - &PageSuggestionStack
        type: StackLayout
        hcenter: true
      - &PageSuggestionButton
        type: Button
        action-string: Go to typed address + Ok
        fixed-width: 150
        fixed-height: 96
        bottom-margin: 0
        skin-foreground-image: Thumbnail Busy Image
      - &PageSuggestionName
        type: Button
        fixed-width: 150
        top-margin: 0
      - &ExtensionSuggestionComposite
        type: Composite
        skin-image: Speed Dial Configuration Dialog Extension Button
      - &ExtensionSuggestionStack
        <<: *PageSuggestionStack
      - &ExtensionSuggestionButton
        <<: *PageSuggestionButton
        action-string: Install Speed Dial extension + Ok
        skin-foreground-image: Extensions 64 Gray
      - &ExtensionSuggestionName
        <<: *PageSuggestionName
    content:
      type: StackLayout
      elements:
        - type: SkinElement
          skin-image: Speed Dial Configuration Dialog Header Skin
          content:
            type: StackLayout
            elements:
              - type: StackLayout
                orientation: horizontal
                elements:
                  - type: Label
                    string: D_SD_LABEL_URL
                  - type: Address
                    name: address_inputbox
                    minimum-width: 0
                    ghost-string: S_ENTER_WEB_ADDRESS_HERE
              - type: Label
                string: S_SEARCH_FIELD_SUGGESTIONS
                top-margin: 24
                name: Suggestions
        - type: SkinElement
          skin-image: Speed Dial Configuration Dialog Suggestions
          content:
            type: GridLayout
            name: suggestions_grid
            elements:
              - elements:
                - <<: *PageSuggestionComposite
                  name: Page0
                  content:
                    <<: *PageSuggestionStack
                    elements:
                      - <<: *PageSuggestionButton
                        name: PageButton0
                      - <<: *PageSuggestionName
                        name: PageName0
                - <<: *PageSuggestionComposite
                  name: Page1
                  content:
                    <<: *PageSuggestionStack
                    elements:
                      - <<: *PageSuggestionButton
                        name: PageButton1
                      - <<: *PageSuggestionName
                        name: PageName1
                - <<: *PageSuggestionComposite
                  name: Page2
                  content:
                    <<: *PageSuggestionStack
                    elements:
                      - <<: *PageSuggestionButton
                        name: PageButton2
                      - <<: *PageSuggestionName
                        name: PageName2
              - elements:
                - <<: *ExtensionSuggestionComposite
                  name: Extension0
                  content:
                    <<: *ExtensionSuggestionStack
                    elements:
                      - <<: *ExtensionSuggestionButton
                        name: ExtensionButton0
                      - <<: *ExtensionSuggestionName
                        name: ExtensionName0
                - <<: *ExtensionSuggestionComposite
                  name: Extension1
                  content:
                    <<: *ExtensionSuggestionStack
                    elements:
                      - <<: *ExtensionSuggestionButton
                        name: ExtensionButton1
                      - <<: *ExtensionSuggestionName
                        name: ExtensionName1
                - <<: *ExtensionSuggestionComposite
                  name: Extension2
                  content:
                    <<: *ExtensionSuggestionStack
                    elements:
                      - <<: *ExtensionSuggestionButton
                        name: ExtensionButton2
                      - <<: *ExtensionSuggestionName
                        name: ExtensionName2
    button-strip:
      <<: *OkCancelButtonStrip
      special-content:
        type: Button
        name: ViewAllExtensions
        string: D_EXTENSION_PANEL_GET_MORE
        action:
          name: "Open url in new page"
          data_string: "https://addons.opera.com/redirect/speeddial-extensions/"

