  - type: SkinElement
    name: Mail Compose Window
    skin-image: Mail Window Background Skin
    content:
      type: SkinElement
      skin-image: Compose Window Background Overlay
      top-margin: 0
      bottom-margin: 0
      left-margin: 0
      right-margin: 0
      dynamic-padding: true
      content:
        type: SkinElement
        skin-image: Compose Window Border Skin
        content:
          type: StackLayout
          top-margin: 0
          bottom-margin: 0
          left-margin: 0
          right-margin: 0
          orientation: vertical
          elements:
            - type: SkinElement
              skin-image: Compose Header Pane
              content:
                type: StackLayout
                orientation: horizontal
                preferred-width: fill
                elements:
                  - type: GridLayout
                    elements:
                      - elements:
                        - type: Label
                          name: cw_From
                          string: DI_IDSTR_M2_COMPOSEMAIL_FROM
                          font-weight: bold
                          skin-image: Compose Header Pane Label
                        - type: StackLayout
                          orientation: horizontal
                          elements:
                            - type: Dropdown
                              name: cw_FromDropdown
                              preferred-width: infinity
                              minimum-width: 15c
                            - type: Dropdown
                              name: cw_EncodingDropdown
                      - elements:
                        - type: Button
                          name: cw_To
                          string: DI_IDSTR_M2_COMPOSEMAIL_TO
                          button-style: toolbar-text
                          font-weight: bold
                          preferred-width: fill
                          preferred-height: fill
                          action: 
                            name: Show Hidden Popup Menu
                            data_string: Compose To Contact Menu
                        - type: ComposeEdit
                          name: cw_ToEdit
                          preferred-width: infinity
                      - elements:
                        - type: Button
                          name: cw_Cc
                          button-style: toolbar-text
                          font-weight: bold
                          string: DI_IDSTR_M2_COMPOSEMAIL_CC
                          preferred-width: fill
                          preferred-height: fill
                          action: 
                            name: Show Hidden Popup Menu
                            data_string: Compose CC Contact Menu
                        - type: ComposeEdit
                          name: cw_CcEdit
                          preferred-width: infinity
                      - elements:
                        - type: Button
                          name: cw_Bcc
                          button-style: toolbar-text
                          font-weight: bold
                          string: S_COMPOSEMAIL_BCC
                          preferred-width: fill
                          preferred-height: fill
                          action: 
                            name: Show Hidden Popup Menu
                            data_string: Compose BCC Contact Menu
                        - type: ComposeEdit
                          name: cw_BccEdit
                          preferred-width: infinity
                      - elements:
                        - type: Label
                          name: cw_Newsgroups
                          font-weight: bold
                          string: S_COMPOSEMAIL_NEWSGROUP
                          skin-image: Compose Header Pane Label
                        - type: ComposeEdit
                          name: cw_NewsgroupsEdit
                          preferred-width: infinity
                      - elements:
                        - type: Label
                          name: cw_Followupto
                          font-weight: bold
                          string: S_COMPOSEMAIL_FOLLOWUP
                          skin-image: Compose Header Pane Label
                        - type: ComposeEdit
                          name: cw_FollowuptoEdit
                          preferred-width: infinity
                      - elements:
                        - type: Label
                          name: cw_Replyto
                          font-weight: bold
                          string: S_COMPOSEMAIL_REPLYTO
                          skin-image: Compose Header Pane Label
                        - type: ComposeEdit
                          name: cw_ReplytoEdit
                          preferred-width: infinity
                      - elements:
                        - type: Label
                          name: cw_Subject
                          font-weight: bold
                          string: DI_IDSTR_M2_COMPOSEMAIL_SUBJECT
                          skin-image: Compose Header Pane Label
                        - type: StackLayout
                          orientation: horizontal
                          left-margin: 0
                          right-margin: 0
                          elements:
                            - type: Edit
                              name: cw_SubjectEdit
                              preferred-width: infinity
                              right-margin: 0
                            - <<: *MailComposeHeaderButton
                              string: S_NORMAL_PRIORITY
                              name: cw_PriorityButton
                              skin-foreground-image: Priority Normal
                              fixed-image: true
                              action: 
                                name: Show Popup Menu
                                data_string: Mail Priority Menu
                            - <<: *MailComposeHeaderButton
                              name: cw_DirectionButton
                              action-string: Change direction to LTR,,,D_MAIL_DIRECTION_LEFT_TO_RIGHT,"Mail Compose Left to right" | Change direction to RTL,,,,"Mail Compose Right to left"
                  - type: SkinElement
                    name: cw_AttachmentArea
                    skin-image: Mail Compose Attachment Section Skin
                    content:
                      type: Treeview
                      name: cw_AttachmentList
                      minimum-width: 15c
                      preferred-width: 40c
                      preferred-height: fill
                      nominal-height: 2c
                      skin-image: Mail Compose Attachment
            - type: RichTextEditor
              name: cw_RichTextEditor
              preferred-width: infinity
              preferred-height: infinity
